AWSTemplateFormatVersion: "2010-09-09"
Description: Knowledge Transfer by GenAIアプリケーションをデプロイするためのCodeBuildプロジェクト

Parameters:
  AllowedIpV4AddressRanges:
    Type: String
    Default: '["0.0.0.0/1","128.0.0.0/1"]'
    Description: フロントエンドWAFで許可するIPv4アドレス範囲（JSON配列形式）

  AllowedIpV6AddressRanges:
    Type: String
    Default: '["0000:0000:0000:0000:0000:0000:0000:0000/1","8000:0000:0000:0000:0000:0000:0000:0000/1"]'
    Description: フロントエンドWAFで許可するIPv6アドレス範囲（JSON配列形式）

  DisableIpv6:
    Type: String
    Default: "false"
    Description: IPv6サポートを無効にするかどうか
    AllowedValues: ["true", "false"]

  BedrockRegion:
    Type: String
    Default: "us-west-2"
    Description: Amazon Bedrockを利用するリージョン

  DeploymentRegion:
    Type: String
    Default: "ap-northeast-1"
    Description: アプリケーションをデプロイするリージョン

  RepoUrl:
    Type: String
    Default: "https://github.com/aws-samples/knowledge-transfer-by-genai.git"
    Description: デプロイするリポジトリのURL

  Branch:
    Type: String
    Default: "main"
    Description: デプロイするブランチ名

  GitTag:
    Type: String
    Default: ""
    Description: デプロイするGitタグ名（指定した場合はブランチよりも優先されます）

Resources:
  ProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AdministratorAccess

  ProjectRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: Project
                    - :*
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: Project
          - Action:
              - codebuild:BatchPutCodeCoverages
              - codebuild:BatchPutTestCases
              - codebuild:CreateReport
              - codebuild:CreateReportGroup
              - codebuild:UpdateReport
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":codebuild:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :report-group/
                  - Ref: Project
                  - -*
        Version: "2012-10-17"
      PolicyName: ProjectRoleDefaultPolicy
      Roles:
        - Ref: ProjectRole

  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE
      EncryptionKey: alias/aws/s3
      Environment:
        # Ref: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:7.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ALLOWED_IPV4_RANGES
            Value: !Ref AllowedIpV4AddressRanges
          - Name: ALLOWED_IPV6_RANGES
            Value: !Ref AllowedIpV6AddressRanges
          - Name: DISABLE_IPV6
            Value: !Ref DisableIpv6
          - Name: BEDROCK_REGION
            Value: !Ref BedrockRegion
          - Name: DEPLOYMENT_REGION
            Value: !Ref DeploymentRegion
          - Name: REPO_URL
            Value: !Ref RepoUrl
          - Name: BRANCH
            Value: !Ref Branch
          - Name: GIT_TAG
            Value: !Ref GitTag
      ServiceRole:
        Fn::GetAtt:
          - ProjectRole
          - Arn
      Source:
        BuildSpec: |-
          {
            "version": 0.2,
            "phases": {
              "install": {
                "runtime-versions": {
                  "nodejs": "20"
                },
                "on-failure": "ABORT",
                "commands": [
                  "npm install -g npm@latest",
                  "npm install -g esbuild",
                  "npm install -g typescript@5.8.3"
                ]
              },
              "build": {
                "commands": [
                  "echo 'ビルドフェーズを開始します...'",
                  "if [ ! -z \"$GIT_TAG\" ]; then\n  git clone $REPO_URL knowledge-transfer\n  cd knowledge-transfer\n  git checkout $GIT_TAG\n  cd ..\nelse\n  git clone --branch $BRANCH $REPO_URL knowledge-transfer\nfi",
                  "cd knowledge-transfer",
                  "echo 'パラメータを設定中...'",
                  "# 既存のcdk.jsonを編集してカスタムパラメータを設定",
                  "ENABLE_IPV6=\"true\"",
                  "if [ \"$DISABLE_IPV6\" = \"true\" ]; then ENABLE_IPV6=\"false\"; fi",
                  "jq '.context.bedrockRegion = \"'\"$BEDROCK_REGION\"'\" | .context.enableIpV6 = '\"$ENABLE_IPV6\"' | .context.allowedIpV4AddressRanges = '$ALLOWED_IPV4_RANGES' | .context.allowedIpV6AddressRanges = '$ALLOWED_IPV6_RANGES'' cdk/cdk.json > cdk/cdk.json.tmp",
                  "mv cdk/cdk.json.tmp cdk/cdk.json",
                  "echo 'CDK設定ファイルを更新しました:'",
                  "cat cdk/cdk.json",
                  "echo 'プロジェクトの準備...'",
                  "# コードのビルド",
                  "npm run build",
                  
                  "# CDKのデプロイ",
                  "cd cdk",
                  "echo 'CDKデプロイの準備...'",
                  "npm ci",
                  "echo 'CDKブートストラップを実行中...'",
                  "npx cdk bootstrap",
                  "echo 'CDKデプロイを実行中...'",
                  "npx cdk deploy --all --require-approval never"
                ]
              },
              "post_build": {
                "commands": [
                  "echo 'デプロイ完了！'",
                  "DISTRIBUTION_URL=$(aws cloudformation describe-stacks --stack-name KnowledgeTransferStack --query \"Stacks[0].Outputs[?OutputKey=='DistributionUrl'].OutputValue\" --output text)",
                  "echo \"フロントエンドURL: $DISTRIBUTION_URL\"",
                  "echo \"KnowledgeTransferStack.DistributionUrl = $DISTRIBUTION_URL\""
                ]
              }
            }
          }
        Type: NO_SOURCE

Outputs:
  ProjectName:
    Value:
      Ref: Project
    Description: CodeBuildプロジェクト名
