/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutAlertsRouteImport } from './routes/_layout/alerts'
import { Route as LayoutAlertAlertIdRouteImport } from './routes/_layout/alert.$alertId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAlertsRoute = LayoutAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlertAlertIdRoute = LayoutAlertAlertIdRouteImport.update({
  id: '/alert/$alertId',
  path: '/alert/$alertId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof LayoutAlertsRoute
  '/alert/$alertId': typeof LayoutAlertAlertIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof LayoutAlertsRoute
  '/alert/$alertId': typeof LayoutAlertAlertIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/alerts': typeof LayoutAlertsRoute
  '/_layout/alert/$alertId': typeof LayoutAlertAlertIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alerts' | '/alert/$alertId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/alert/$alertId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/alerts'
    | '/_layout/alert/$alertId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/alerts': {
      id: '/_layout/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof LayoutAlertsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/alert/$alertId': {
      id: '/_layout/alert/$alertId'
      path: '/alert/$alertId'
      fullPath: '/alert/$alertId'
      preLoaderRoute: typeof LayoutAlertAlertIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAlertsRoute: typeof LayoutAlertsRoute
  LayoutAlertAlertIdRoute: typeof LayoutAlertAlertIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAlertsRoute: LayoutAlertsRoute,
  LayoutAlertAlertIdRoute: LayoutAlertAlertIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
